version: '3'

services:
    react-app:
        build: .    
        #entrypoint: ./.docker/entrypoint.sh
        entrypoint: ["sh", "./.docker/entrypoint.sh"]
        ports:
            - "3001:3001"
        volumes: 
            - .:/home/node/app